const LANGUAGES = [
  { code: 'fr', name: { fr: 'Français', en: 'French', es: 'Francés' } },
  { code: 'en', name: { fr: 'Anglais', en: 'English', es: 'Inglés' } },
  { code: 'es', name: { fr: 'Espagnol', en: 'Spanish', es: 'Español' } },
  { code: 'de', name: { fr: 'Allemand', en: 'German', es: 'Alemán' } },
  { code: 'it', name: { fr: 'Italien', en: 'Italian', es: 'Italiano' } },
  { code: 'pt', name: { fr: 'Portugais', en: 'Portuguese', es: 'Portugués' } },
  { code: 'nl', name: { fr: 'Néerlandais', en: 'Dutch', es: 'Neerlandés' } },
  { code: 'pl', name: { fr: 'Polonais', en: 'Polish', es: 'Polaco' } },
  { code: 'ro', name: { fr: 'Roumain', en: 'Romanian', es: 'Rumano' } },
  { code: 'sv', name: { fr: 'Suédois', en: 'Swedish', es: 'Sueco' } },
  { code: 'da', name: { fr: 'Danois', en: 'Danish', es: 'Danés' } },
  { code: 'fi', name: { fr: 'Finnois', en: 'Finnish', es: 'Finés' } },
  { code: 'el', name: { fr: 'Grec', en: 'Greek', es: 'Griego' } },
  { code: 'cs', name: { fr: 'Tchèque', en: 'Czech', es: 'Checo' } },
  { code: 'hu', name: { fr: 'Hongrois', en: 'Hungarian', es: 'Húngaro' } },
  { code: 'hr', name: { fr: 'Croate', en: 'Croatian', es: 'Croata' } },
  { code: 'bg', name: { fr: 'Bulgare', en: 'Bulgarian', es: 'Búlgaro' } },
  { code: 'sk', name: { fr: 'Slovaque', en: 'Slovak', es: 'Eslovaco' } },
  { code: 'sl', name: { fr: 'Slovène', en: 'Slovenian', es: 'Esloveno' } },
  { code: 'et', name: { fr: 'Estonien', en: 'Estonian', es: 'Estonio' } },
  { code: 'lv', name: { fr: 'Letton', en: 'Latvian', es: 'Letón' } },
  { code: 'lt', name: { fr: 'Lituanien', en: 'Lithuanian', es: 'Lituano' } },
  { code: 'ga', name: { fr: 'Irlandais', en: 'Irish', es: 'Irlandés' } },
  { code: 'mt', name: { fr: 'Maltais', en: 'Maltese', es: 'Maltés' } },
  { code: 'ar', name: { fr: 'Arabe', en: 'Arabic', es: 'Árabe' } },
  { code: 'tr', name: { fr: 'Turc', en: 'Turkish', es: 'Turco' } },
  { code: 'ru', name: { fr: 'Russe', en: 'Russian', es: 'Ruso' } },
  { code: 'uk', name: { fr: 'Ukrainien', en: 'Ukrainian', es: 'Ucraniano' } },
  { code: 'sr', name: { fr: 'Serbe', en: 'Serbian', es: 'Serbio' } },
  { code: 'no', name: { fr: 'Norvégien', en: 'Norwegian', es: 'Noruego' } },
];

module.exports = { LANGUAGES };
