const SPORTS = [
  { id: 1, key: 'football', name: { fr: 'Football', en: 'Football (Soccer)', es: 'Fútbol' } },
  { id: 2, key: 'basketball', name: { fr: 'Basketball', en: 'Basketball', es: 'Baloncesto' } },
  { id: 3, key: 'tennis', name: { fr: 'Tennis', en: 'Tennis', es: 'Tenis' } },
  { id: 4, key: 'swimming', name: { fr: 'Natation', en: 'Swimming', es: 'Natación' } },
  { id: 5, key: 'running', name: { fr: 'Course à pied', en: 'Running', es: 'Running' } },
  { id: 6, key: 'cycling', name: { fr: 'Cyclisme', en: 'Cycling', es: 'Ciclismo' } },
  { id: 7, key: 'volleyball', name: { fr: 'Volleyball', en: 'Volleyball', es: 'Voleibol' } },
  { id: 8, key: 'handball', name: { fr: 'Handball', en: 'Handball', es: 'Balonmano' } },
  { id: 9, key: 'rugby', name: { fr: 'Rugby', en: 'Rugby', es: 'Rugby' } },
  { id: 10, key: 'table_tennis', name: { fr: 'Tennis de table', en: 'Table Tennis', es: 'Tenis de mesa' } },
  { id: 11, key: 'badminton', name: { fr: 'Badminton', en: 'Badminton', es: 'Bádminton' } },
  { id: 12, key: 'golf', name: { fr: 'Golf', en: 'Golf', es: 'Golf' } },
  { id: 13, key: 'boxing', name: { fr: 'Boxe', en: 'Boxing', es: 'Boxeo' } },
  { id: 14, key: 'judo', name: { fr: 'Judo', en: 'Judo', es: 'Judo' } },
  { id: 15, key: 'karate', name: { fr: 'Karaté', en: 'Karate', es: 'Karate' } },
  { id: 16, key: 'taekwondo', name: { fr: 'Taekwondo', en: 'Taekwondo', es: 'Taekwondo' } },
  { id: 17, key: 'fencing', name: { fr: 'Escrime', en: 'Fencing', es: 'Esgrima' } },
  { id: 18, key: 'gymnastics', name: { fr: 'Gymnastique', en: 'Gymnastics', es: 'Gimnasia' } },
  { id: 19, key: 'athletics', name: { fr: 'Athlétisme', en: 'Athletics', es: 'Atletismo' } },
  { id: 20, key: 'skiing', name: { fr: 'Ski', en: 'Skiing', es: 'Esquí' } },
  { id: 21, key: 'snowboarding', name: { fr: 'Snowboard', en: 'Snowboarding', es: 'Snowboard' } },
  { id: 22, key: 'ice_hockey', name: { fr: 'Hockey sur glace', en: 'Ice Hockey', es: 'Hockey sobre hielo' } },
  { id: 23, key: 'field_hockey', name: { fr: 'Hockey sur gazon', en: 'Field Hockey', es: 'Hockey hierba' } },
  { id: 24, key: 'cricket', name: { fr: 'Cricket', en: 'Cricket', es: 'Críquet' } },
  { id: 25, key: 'rowing', name: { fr: 'Aviron', en: 'Rowing', es: 'Remo' } },
  { id: 26, key: 'sailing', name: { fr: 'Voile', en: 'Sailing', es: 'Vela' } },
  { id: 27, key: 'surfing', name: { fr: 'Surf', en: 'Surfing', es: 'Surf' } },
  { id: 28, key: 'climbing', name: { fr: 'Escalade', en: 'Climbing', es: 'Escalada' } },
  { id: 29, key: 'skateboarding', name: { fr: 'Skateboard', en: 'Skateboarding', es: 'Skateboard' } },
  { id: 30, key: 'horse_riding', name: { fr: 'Équitation', en: 'Horse Riding', es: 'Equitación' } },
  { id: 31, key: 'archery', name: { fr: 'Tir à l\'arc', en: 'Archery', es: 'Tiro con arco' } },
  { id: 32, key: 'shooting', name: { fr: 'Tir sportif', en: 'Sport Shooting', es: 'Tiro deportivo' } },
  { id: 33, key: 'triathlon', name: { fr: 'Triathlon', en: 'Triathlon', es: 'Triatlón' } },
  { id: 34, key: 'weightlifting', name: { fr: 'Haltérophilie', en: 'Weightlifting', es: 'Halterofilia' } },
  { id: 35, key: 'crossfit', name: { fr: 'CrossFit', en: 'CrossFit', es: 'CrossFit' } },
  { id: 36, key: 'yoga', name: { fr: 'Yoga', en: 'Yoga', es: 'Yoga' } },
  { id: 37, key: 'pilates', name: { fr: 'Pilates', en: 'Pilates', es: 'Pilates' } },
  { id: 38, key: 'dance', name: { fr: 'Danse', en: 'Dance', es: 'Danza' } },
  { id: 39, key: 'figure_skating', name: { fr: 'Patinage artistique', en: 'Figure Skating', es: 'Patinaje artístico' } },
  { id: 40, key: 'water_polo', name: { fr: 'Water-polo', en: 'Water Polo', es: 'Waterpolo' } },
  { id: 41, key: 'diving', name: { fr: 'Plongée', en: 'Diving', es: 'Buceo' } },
  { id: 42, key: 'canoeing', name: { fr: 'Canoë', en: 'Canoeing', es: 'Piragüismo' } },
  { id: 43, key: 'kayaking', name: { fr: 'Kayak', en: 'Kayaking', es: 'Kayak' } },
  { id: 44, key: 'windsurfing', name: { fr: 'Planche à voile', en: 'Windsurfing', es: 'Windsurf' } },
  { id: 45, key: 'kitesurfing', name: { fr: 'Kitesurf', en: 'Kitesurfing', es: 'Kitesurf' } },
  { id: 46, key: 'padel', name: { fr: 'Padel', en: 'Padel', es: 'Pádel' } },
  { id: 47, key: 'squash', name: { fr: 'Squash', en: 'Squash', es: 'Squash' } },
  { id: 48, key: 'bowling', name: { fr: 'Bowling', en: 'Bowling', es: 'Bolos' } },
  { id: 49, key: 'petanque', name: { fr: 'Pétanque', en: 'Pétanque', es: 'Petanca' } },
  { id: 50, key: 'darts', name: { fr: 'Fléchettes', en: 'Darts', es: 'Dardos' } },
  { id: 51, key: 'billiards', name: { fr: 'Billard', en: 'Billiards', es: 'Billar' } },
  { id: 52, key: 'futsal', name: { fr: 'Futsal', en: 'Futsal', es: 'Futsal' } },
  { id: 53, key: 'beach_volleyball', name: { fr: 'Beach-volley', en: 'Beach Volleyball', es: 'Vóley playa' } },
  { id: 54, key: 'lacrosse', name: { fr: 'Lacrosse', en: 'Lacrosse', es: 'Lacrosse' } },
  { id: 55, key: 'baseball', name: { fr: 'Baseball', en: 'Baseball', es: 'Béisbol' } },
  { id: 56, key: 'softball', name: { fr: 'Softball', en: 'Softball', es: 'Sóftbol' } },
  { id: 57, key: 'american_football', name: { fr: 'Football américain', en: 'American Football', es: 'Fútbol americano' } },
  { id: 58, key: 'wrestling', name: { fr: 'Lutte', en: 'Wrestling', es: 'Lucha' } },
  { id: 59, key: 'mma', name: { fr: 'MMA', en: 'MMA', es: 'MMA' } },
  { id: 60, key: 'kickboxing', name: { fr: 'Kickboxing', en: 'Kickboxing', es: 'Kickboxing' } },
  { id: 61, key: 'muay_thai', name: { fr: 'Muay Thai', en: 'Muay Thai', es: 'Muay Thai' } },
  { id: 62, key: 'bjj', name: { fr: 'Jiu-Jitsu brésilien', en: 'Brazilian Jiu-Jitsu', es: 'Jiu-Jitsu brasileño' } },
  { id: 63, key: 'aikido', name: { fr: 'Aïkido', en: 'Aikido', es: 'Aikido' } },
  { id: 64, key: 'krav_maga', name: { fr: 'Krav Maga', en: 'Krav Maga', es: 'Krav Maga' } },
  { id: 65, key: 'trail_running', name: { fr: 'Trail', en: 'Trail Running', es: 'Trail Running' } },
  { id: 66, key: 'mountain_biking', name: { fr: 'VTT', en: 'Mountain Biking', es: 'Bicicleta de montaña' } },
  { id: 67, key: 'roller_skating', name: { fr: 'Roller', en: 'Roller Skating', es: 'Patinaje' } },
  { id: 68, key: 'ice_skating', name: { fr: 'Patinage sur glace', en: 'Ice Skating', es: 'Patinaje sobre hielo' } },
  { id: 69, key: 'cross_country_skiing', name: { fr: 'Ski de fond', en: 'Cross-Country Skiing', es: 'Esquí de fondo' } },
  { id: 70, key: 'biathlon', name: { fr: 'Biathlon', en: 'Biathlon', es: 'Biatlón' } },
  { id: 71, key: 'curling', name: { fr: 'Curling', en: 'Curling', es: 'Curling' } },
  { id: 72, key: 'polo', name: { fr: 'Polo', en: 'Polo', es: 'Polo' } },
  { id: 73, key: 'parkour', name: { fr: 'Parkour', en: 'Parkour', es: 'Parkour' } },
  { id: 74, key: 'trampoline', name: { fr: 'Trampoline', en: 'Trampoline', es: 'Trampolín' } },
  { id: 75, key: 'orienteering', name: { fr: 'Course d\'orientation', en: 'Orienteering', es: 'Orientación' } },
  { id: 76, key: 'hiking', name: { fr: 'Randonnée', en: 'Hiking', es: 'Senderismo' } },
  { id: 77, key: 'nordic_walking', name: { fr: 'Marche nordique', en: 'Nordic Walking', es: 'Marcha nórdica' } },
  { id: 78, key: 'calisthenics', name: { fr: 'Callisthénie', en: 'Calisthenics', es: 'Calistenia' } },
  { id: 79, key: 'paddle_boarding', name: { fr: 'Stand-up paddle', en: 'Stand-Up Paddle', es: 'Paddle surf' } },
  { id: 80, key: 'rock_climbing', name: { fr: 'Escalade en bloc', en: 'Bouldering', es: 'Búlder' } },
];

module.exports = { SPORTS };
